Make sure the return value is no longer of a Algebraic type
This is usually the case for the spectral invariants. This leads to the following error when a division is needed of these elements:

    TypeError: no canonical coercion from Algebraic Field to Rational Field